# Generated by Django 5.0.7 on 2024-07-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lovelace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lovelace_name', models.CharField(max_length=10)),
                ('lovelace_id', models.CharField(max_length=5)),
                ('lovelace_descirption', models.TextField()),
                ('lovelace_hours', models.PositiveSmallIntegerField()),
                ('lovelace_trainer_name', models.CharField(max_length=10)),
                ('lovelace_capacity', models.PositiveSmallIntegerField()),
                ('room_number', models.PositiveSmallIntegerField()),
                ('meeting_time', models.PositiveSmallIntegerField()),
                ('grade_level', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
